-- 操作介紹：依功能分類建成草稿（全部未發佈）
-- 可重複執行：已存在的 slug 不覆蓋（避免蓋掉你已改寫的內容）
-- 前台在資料夾／文章發佈前不會出現；請到 /admin/operation-guides.html 依序改寫後公開
-- 區塊內文（用途／操作／注意）請再執行 docs/add-help-guides-draft-content.sql
-- 英文欄位留空，中文修正後再翻譯

INSERT INTO public.help_guide_folders (slug, title, title_en, sort_order, is_published)
VALUES
    ('getting-started', '開始使用', '', 10, false),
    ('design-draft', '設計稿', '', 20, false),
    ('materials', '材料組合', '', 30, false),
    ('print-asset', '印花', '', 40, false),
    ('promo-image', '情境圖', '', 50, false),
    ('promo-camera', '商攝導演', '', 60, false),
    ('pattern-extract', '圖樣提取', '', 70, false),
    ('design-to-physical', '寫實化', '', 80, false),
    ('scene-sim', '實境模擬', '', 90, false),
    ('my-assets', '我的數位資產', '', 100, false),
    ('gallery', '圖庫找廠商', '', 110, false),
    ('design-direction', '設計風向', '', 120, false),
    ('vendor-start', '製造商入門', '', 200, false),
    ('vendor-portfolio', '展示案例', '', 210, false),
    ('vendor-materials', '素材管理', '', 220, false),
    ('vendor-embed', 'Embed 說明', '', 230, false),
    ('vendor-inquiries', '詢價', '', 240, false),
    ('vendor-profile', '廠商公開首頁', '', 250, false),
    ('vendor-sourcing', '上游採購', '', 260, false),
    ('supplier-catalog', '供應商上架', '', 300, false),
    ('supplier-profile', '供應商公開頁', '', 310, false),
    ('membership', '方案與點數', '', 400, false),
    ('faq', '常見問題', '', 500, false)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.help_guide_pages (
    folder_id, slug, title, title_en, summary, summary_en, blocks_json, sort_order, is_published
)
SELECT
    f.id,
    v.slug,
    v.title,
    '',
    v.summary,
    '',
    jsonb_build_array(jsonb_build_object(
        'type', 'text',
        'sort', 0,
        'text', '這篇仍是草稿，尚未發佈。請在後台改寫後再公開。' || E'\n\n' || v.body,
        'text_en', ''
    )),
    v.sort_order,
    false
FROM (VALUES
    -- 開始使用
    ('getting-started', 'overview', '總覽', 'Overview',
     '同一個 Email 帳號，沒有訂製者／製造商／供應商角色切換。',
     'One account; no role switch between designer, manufacturer, and supplier.',
     0,
     E'## 同一帳號\n（待補）同一個 Email，①②③ 只是「我的功能」分區標題，不是權限角色。\n\n## 選單怎麼看\n（待補）客製產品、設計風向、方案與定價、我的功能。\n\n## 兩項限制（摘要）\n- 免費帳號不可上傳產品與素材（展示案例除外）\n- 沒有至少 1 件展示中作品，不可匯入產業供應商目錄',
     E'## One account\n(Draft)\n\n## Menus\n(Draft)\n\n## Two limits\n- Free accounts cannot upload products or assets (portfolio cases excepted)\n- Importing supplier catalog needs at least one public portfolio case'),
    ('getting-started', 'login', '註冊與登入', 'Sign in',
     'Google 與 Email 密碼可並存在同一帳號；可設定密碼與忘記密碼。',
     'Google and email-password can both be used on the same account.',
     10,
     E'## 用 Google 登入\n（待補）\n\n## 用 Email 與密碼\n（待補）\n\n## 同一帳號綁兩種方式\n（待補）\n\n## 忘記密碼\n（待補）',
     E'## Google\n(Draft)\n\n## Email and password\n(Draft)\n\n## Both methods on one account\n(Draft)\n\n## Forgot password\n(Draft)'),
    ('getting-started', 'first-visit', '第一次來', 'First visit',
     '建議先看設計稿或商攝，再決定要不要建立廠商資料。',
     'Suggested first path: design draft or promo camera.',
     20,
     E'## 想做設計稿\n到「客製產品 → 設計稿」。\n\n## 想做行銷影像\n到「商攝導演」或「情境圖」。\n\n## 想當廠商被找到\n先建立廠商資料，再上傳展示案例與素材。',
     E'## Design\nCustom → Design draft.\n\n## Marketing images\nPromo camera or scene images.\n\n## Be found as a maker\nCreate manufacturer profile, then portfolio and materials.'),

    -- 設計稿
    ('design-draft', 'overview', '總覽', 'Overview',
     '同一工作區兩種進法：無樣版（只靠描述／分類）與有樣版（帶入廠商或官方版型）。',
     'Same workspace: no template, or with a vendor / official template.',
     0,
     E'工具頁：/custom-product.html\n\n## 無樣版\n（待補）選分類、寫描述、可加本機參考圖後生圖。\n\n## 有樣版\n（待補）從廠商版型或官方版型帶入後再設計。\n\n相關：\n- /help/design-draft/references\n- /help/design-draft/vendor-styles\n- /help/design-draft/official-templates',
     E'Tool: /custom-product.html\n\n## No template\n(Draft)\n\n## With a template\n(Draft) Vendor styles or official templates.'),
    ('design-draft', 'references', '參考圖', 'References',
     '本機上傳、廠商素材庫、官方版型，三種來源怎麼選。',
     'Local upload, vendor library, or official templates.',
     10,
     E'## 本機上傳\n（待補）\n\n## 從廠商素材庫選擇\n（待補）請先選好主分類；沒圖時見常見問題。\n\n## 官方版型\n（待補）',
     E'## Local upload\n(Draft)\n\n## Vendor library\n(Draft)\n\n## Official templates\n(Draft)'),
    ('design-draft', 'vendor-styles', '廠商版型', 'Vendor styles',
     '公開列表瀏覽廠商版型，再用此版型進入設計稿。',
     'Browse public vendor styles, then design with one.',
     20,
     E'列表頁：/vendor-styles/\n\n## 怎麼瀏覽\n（待補）獨立列表頁，不是設計頁分頁。\n\n## 用此版型設計\n（待補）會深鏈進設計稿並帶入該版型。',
     E'List: /vendor-styles/\n\n## Browse\n(Draft)\n\n## Design with this style\n(Draft)'),
    ('design-draft', 'official-templates', '官方版型', 'Official templates',
     '公開列表瀏覽官方版型，再用此版型進入設計稿。',
     'Browse official templates, then design with one.',
     30,
     E'列表頁：/official-templates/\n\n## 怎麼瀏覽\n（待補）\n\n## 用此版型設計\n（待補）',
     E'List: /official-templates/\n\n## Browse\n(Draft)\n\n## Design with this template\n(Draft)'),
    ('design-draft', 'generate-and-save', '生成與儲存', 'Generate and save',
     '生圖、存到我的數位資產，以及要不要出現在媒體牆。',
     'Generate, save to My assets, and media-wall visibility.',
     40,
     E'## 生成\n（待補）點數以頁面顯示為準。\n\n## 存到我的數位資產\n（待補）\n\n## 不上媒體牆\n見 /help/membership/hide-from-wall',
     E'## Generate\n(Draft)\n\n## Save to My assets\n(Draft)\n\n## Hide from media wall\nSee /help/membership/hide-from-wall'),

    -- 以風格／行銷／輔助
    ('materials', 'overview', '總覽', 'Overview',
     '材料組合（含雙色／配色範例）怎麼用。',
     'Material combinations, including dual-color palettes.',
     0,
     E'工具頁：/client/material-dual-color.html\n\n## 怎麼開始\n（待補）\n\n## 配色範例\n（待補）\n\n## 結果存到哪\n（待補）',
     E'Tool: /client/material-dual-color.html\n\n## Start\n(Draft)\n\n## Palettes\n(Draft)'),
    ('print-asset', 'overview', '總覽', 'Overview',
     '印花工具怎麼用。',
     'How to use print assets.',
     0,
     E'工具頁：/client/print-asset.html\n\n## 怎麼開始\n（待補）\n\n## 結果存到哪\n（待補）',
     E'Tool: /client/print-asset.html\n\n## Start\n(Draft)'),
    ('promo-image', 'overview', '總覽', 'Overview',
     '情境圖：把產品放進場景的行銷圖。',
     'Scene images for marketing.',
     0,
     E'工具頁：/promo-image/\n\n## 怎麼開始\n（待補）\n\n## 與商攝導演的差別\n情境圖偏場景合成；商攝導演偏拍攝模擬（產品／空間／人像）。',
     E'Tool: /promo-image/\n\n## Start\n(Draft)\n\n## vs promo camera\n(Draft)'),

    ('promo-camera', 'overview', '總覽', 'Overview',
     '商攝導演三種模式：產品、空間、人像。官網與手機 App 共用帳號與點數。',
     'Three modes: product, space, portrait. Same account and credits on web and app.',
     0,
     E'工具頁：/promo-camera\n手機：/promo-camera-app\n\n## 三種模式\n- 產品攝影 → /help/promo-camera/product\n- 空間攝影 → /help/promo-camera/space\n- 人像攝影 → /help/promo-camera/portrait\n\n## 點數\n以頁面顯示為準。\n\n## 設計頁嵌入\n（待補）設計稿可嵌入商攝。',
     E'Tool: /promo-camera\nApp: /promo-camera-app\n\n## Modes\n- Product → /help/promo-camera/product\n- Space → /help/promo-camera/space\n- Portrait → /help/promo-camera/portrait'),
    ('promo-camera', 'product', '產品攝影', 'Product photography',
     '商攝導演：產品攝影模式。',
     'Promo camera: product mode.',
     10,
     E'## 什麼時候用\n（待補）\n\n## 操作步驟\n（待補）\n\n## 解析度與點數\n（待補）以頁面顯示為準。',
     E'## When to use\n(Draft)\n\n## Steps\n(Draft)\n\n## Resolution and credits\n(Draft)'),
    ('promo-camera', 'space', '空間攝影', 'Space photography',
     '平面配置 → 空間地圖 → 地圖標記 → 平視攝影。',
     'Floor plan → space map → markers → eye-level shot.',
     20,
     E'## 平面配置\n（待補）\n\n## 空間地圖\n（待補）\n\n## 地圖標記\n（待補）A–Z 標記。\n\n## 平視攝影\n（待補）\n\n## 解析度與點數\n（待補）2K／4K 以頁面顯示為準。',
     E'## Floor plan\n(Draft)\n\n## Space map\n(Draft)\n\n## Markers\n(Draft)\n\n## Eye-level\n(Draft)\n\n## Resolution and credits\n(Draft)'),
    ('promo-camera', 'portrait', '人像攝影', 'Portrait photography',
     '商攝導演：人像攝影模式。',
     'Promo camera: portrait mode.',
     30,
     E'## 什麼時候用\n（待補）\n\n## 操作步驟\n（待補）\n\n## 解析度與點數\n（待補）',
     E'## When to use\n(Draft)\n\n## Steps\n(Draft)\n\n## Resolution and credits\n(Draft)'),
    ('promo-camera', 'pwa-app', '手機 App', 'Mobile app',
     '線上 PWA 與官網同一帳號、同一點數。',
     'PWA uses the same MatchDO account and credits.',
     40,
     E'網址：/promo-camera-app\n\n## 與官網的關係\n同一帳號、同一點數；功能以商攝為主，不是整站。\n\n## 如何安裝到手機\n（待補）',
     E'URL: /promo-camera-app\n\n## Same account\n(Draft)\n\n## Install\n(Draft)'),

    ('pattern-extract', 'overview', '總覽', 'Overview',
     '圖樣提取：從數位資產選圖提取圖樣（避免侵權，不從任意上傳圖）。',
     'Extract a pattern from a digital asset (not arbitrary uploads).',
     0,
     E'工具頁：/pattern-extract/\n\n## 怎麼開始\n（待補）請從數位資產選圖。\n\n## 結果存到哪\n（待補）',
     E'Tool: /pattern-extract/\n\n## Start\n(Draft)'),
    ('design-to-physical', 'overview', '總覽', 'Overview',
     '寫實化：把設計稿轉成更接近實物的影像。',
     'Make a design look more like a physical product.',
     0,
     E'工具頁：/design-to-physical/\n\n## 怎麼開始\n（待補）\n\n## 結果存到哪\n（待補）',
     E'Tool: /design-to-physical/\n\n## Start\n(Draft)'),
    ('scene-sim', 'overview', '總覽', 'Overview',
     '實境模擬：把設計放到真實場景。',
     'Place a design into a real scene.',
     0,
     E'工具頁：/scene-sim/\n\n## 怎麼開始\n（待補）可上傳參考場景。\n\n## 與情境圖的差別\n（待補）',
     E'Tool: /scene-sim/\n\n## Start\n(Draft)'),
    ('my-assets', 'overview', '總覽', 'Overview',
     '我的數位資產：設計稿與生成結果的收藏處。',
     'My digital assets: saved drafts and generations.',
     0,
     E'工具頁：/client/my-custom-products.html\n\n## 這裡有什麼\n（待補）\n\n## 怎麼再拿去設計或商攝\n（待補）',
     E'Tool: /client/my-custom-products.html\n\n## What is here\n(Draft)'),
    ('gallery', 'overview', '總覽', 'Overview',
     '圖庫找廠商：從作品／圖庫找到製作方。',
     'Find makers from the gallery.',
     0,
     E'工具頁：/custom/gallery.html\n\n## 怎麼找\n（待補）\n\n## 如何聯絡或引用\n（待補）',
     E'Tool: /custom/gallery.html\n\n## Browse\n(Draft)'),

    ('design-direction', 'overview', '總覽', 'Overview',
     '設計風向（測試中）：意圖分析、我的設計風向、找製作方。',
     'Design direction (beta): intent, my directions, find makers.',
     0,
     E'此區標示測試中。\n\n## 入口\n頂部「設計風向」。\n\n相關：\n- /help/design-direction/intent\n- /help/design-direction/my-direction\n- /help/design-direction/find-makers',
     E'Beta.\n\n## Entry\nTop nav: Design direction.'),
    ('design-direction', 'intent', '設計意圖分析', 'Intent analysis',
     '描述或上傳後分析設計意圖。',
     'Analyze design intent.',
     10,
     E'## 怎麼開始\n（待補）\n\n## 結果怎麼用\n（待補）',
     E'## Start\n(Draft)'),
    ('design-direction', 'my-direction', '我的設計風向', 'My directions',
     '已存的設計風向結果。',
     'Saved design-direction results.',
     20,
     E'## 在哪裡看\n（待補）我的數位資產也可切到設計風向檢視。\n\n## 怎麼再編輯\n（待補）',
     E'## Where\n(Draft)'),
    ('design-direction', 'find-makers', '找製作方', 'Find makers',
     '依設計風向找製作方。',
     'Find makers from a design direction.',
     30,
     E'工具頁：/client/find-makers.html\n\n## 怎麼開始\n（待補）',
     E'Tool: /client/find-makers.html\n\n## Start\n(Draft)'),

    -- 廠商區
    ('vendor-start', 'overview', '總覽', 'Overview',
     '建立廠商資料、進入控制台。同一帳號即可，不必另開角色。',
     'Create a manufacturer profile and open the dashboard.',
     0,
     E'控制台：/client/manufacturer-dashboard.html\n\n## 建立廠商資料\n（待補）\n\n## 控制台有哪些\n展示案例、素材管理、詢價、公開首頁。\n\n## 免費帳號能做什麼\n展示案例可上傳；產品／素材上傳需付費方案。',
     E'Dashboard: /client/manufacturer-dashboard.html\n\n## Create profile\n(Draft)\n\n## What is in the dashboard\n(Draft)'),
    ('vendor-portfolio', 'overview', '總覽', 'Overview',
     '展示案例：系列圖與對照圖。同一頁兩種作品形態。',
     'Portfolio: series images and before/after comparisons.',
     0,
     E'工具頁：/client/manufacturer-portfolio.html\n\n## 系列圖\n（待補）\n\n## 對照圖\n（待補）\n\n## 為什麼需要展示中作品\n至少 1 件展示中作品，才能匯入產業供應商目錄。',
     E'Tool: /client/manufacturer-portfolio.html\n\n## Series\n(Draft)\n\n## Comparison\n(Draft)'),
    ('vendor-materials', 'overview', '總覽', 'Overview',
     '素材管理：產品版型、材料版型、零件版型。同一頁不同類型。',
     'Materials: product, material, and part styles in one page.',
     0,
     E'工具頁：/client/manufacturer-materials.html\n\n## 產品版型\n（待補）\n\n## 材料版型\n（待補）\n\n## 零件版型\n（待補）\n\n## 主分類必選\n設計者在設計稿選相同分類時，才能在廠商庫看到你的素材。\n\n## 免費不能上傳\n見 /help/membership/free-limits',
     E'Tool: /client/manufacturer-materials.html\n\n## Product styles\n(Draft)\n\n## Material styles\n(Draft)\n\n## Part styles\n(Draft)'),
    ('vendor-embed', 'overview', '總覽', 'Overview',
     '把模擬／選版型嵌到外站。',
     'Embed the simulator on another site.',
     0,
     E'## 什麼是 Embed\n（待補）給外站引用，不是設計頁分頁。\n\n## 如何取得嵌入碼\n（待補）\n\n## 注意事項\n（待補）',
     E'## What it is\n(Draft)\n\n## How to get the embed code\n(Draft)'),
    ('vendor-inquiries', 'overview', '總覽', 'Overview',
     '查看設計者傳來的詢價。',
     'View incoming inquiries.',
     0,
     E'## 在哪裡看\n（待補）廠商控制台 → 詢價。\n\n## 如何回覆\n（待補）',
     E'## Where\n(Draft)\n\n## Reply\n(Draft)'),
    ('vendor-profile', 'overview', '總覽', 'Overview',
     '廠商公開首頁（可被搜尋），不是後台控制台。',
     'Public vendor homepage (indexable), not the private dashboard.',
     0,
     E'## 公開頁與後台的差別\n公開頁給設計者看；控制台只有你自己能進。\n\n## 如何分享\n（待補）',
     E'## Public vs dashboard\n(Draft)\n\n## Share\n(Draft)'),
    ('vendor-sourcing', 'overview', '總覽', 'Overview',
     '上游採購（B 線）：瀏覽產業供應商目錄並匯入到自己的素材庫。',
     'Browse supplier catalogs and import into your library.',
     0,
     E'## 什麼是上游採購\n製造商引用產業供應商的產品／材料目錄。\n\n## 匯入條件\n需至少 1 件展示中作品。\n\n## 怎麼匯入\n（待補）',
     E'## What it is\n(Draft)\n\n## Import requirement\nAt least one public portfolio case.\n\n## Import steps\n(Draft)'),

    -- 供應商
    ('supplier-catalog', 'overview', '總覽', 'Overview',
     '產業供應商上架數位產品庫（產品／材料）。與廠商素材管理是不同頁。',
     'Industry suppliers list catalog items. Different from manufacturer materials.',
     0,
     E'## 這和廠商素材管理有何不同\n③ 上架的是供應商目錄，供製造商匯入；② 素材管理是製造商自己給設計者引用的版型。\n\n## 怎麼上架\n（待補）\n\n## 免費不能上傳\n見 /help/membership/free-limits',
     E'## vs manufacturer materials\n(Draft)\n\n## How to list\n(Draft)'),
    ('supplier-profile', 'overview', '總覽', 'Overview',
     '供應商公開頁，以及製造商引用紀錄。',
     'Public supplier page and manufacturer import history.',
     0,
     E'## 公開頁\n（待補）\n\n## 製造商引用紀錄\n（待補）',
     E'## Public page\n(Draft)\n\n## Import history\n(Draft)'),

    -- 方案
    ('membership', 'overview', '總覽', 'Overview',
     '訂閱方案的每月點數，與單次儲值不同。',
     'Monthly subscription credits vs one-time top-up.',
     0,
     E'方案頁：/subscription-plans.html\n點數：/credits.html\n\n## 訂閱每月點數\n（待補）\n\n## 單次儲值\n見 /help/membership/top-up\n\n## 各功能大概扣多少\n見 /help/faq',
     E'Plans: /subscription-plans.html\nCredits: /credits.html\n\n## Monthly grant\n(Draft)\n\n## Top-up\nSee /help/membership/top-up'),
    ('membership', 'top-up', '儲值', 'Top-up',
     '單次儲值點數，與訂閱每月贈點分開看。',
     'One-time credit packs, separate from monthly plan grants.',
     10,
     E'## 怎麼儲值\n（待補）我的點數頁。\n\n## 和訂閱的差別\n訂閱是每月給點；儲值是一次買點。',
     E'## How\n(Draft)\n\n## vs subscription\n(Draft)'),
    ('membership', 'hide-from-wall', '作品不上媒體牆', 'Hide from media wall',
     '生成或公開時選擇不要出現在首頁靈感牆。',
     'Keep a work off the public media wall.',
     20,
     E'## 在哪裡勾選\n（待補）設計稿／儲存時。\n\n## 不上牆還會在哪裡\n仍在我的數位資產。',
     E'## Where to opt out\n(Draft)\n\n## Where it still appears\nMy digital assets.'),
    ('membership', 'free-limits', '免費帳號限制', 'Free-plan limits',
     '免費不可上傳產品與素材；展示案例仍可上傳。',
     'Free plans cannot upload products or assets; portfolio cases are allowed.',
     30,
     E'## 不能上傳什麼\n產品（供應商目錄）與素材（廠商版型／材料／零件）。\n\n## 仍可以做什麼\n展示案例、設計稿生圖（依點數）、看說明。\n\n## 管理員／測試員\n不受此限。',
     E'## What you cannot upload\n(Draft)\n\n## What you can still do\n(Draft)'),

    -- FAQ
    ('faq', 'overview', '總覽', 'Overview',
     '點數、素材庫沒圖、如何讓設計者看到素材。',
     'Credits, empty vendor library, and how designers see your assets.',
     0,
     E'## 點數怎麼算？\n（待補）產品設計：無參考圖／有參考圖以頁面為準。商攝、實境模擬、圖樣提取各依該頁顯示。見方案與點數。\n\n## 從廠商素材庫選擇時沒有圖？\n請先選好主分類。若該分類尚無廠商上傳，會顯示尚無素材。\n\n## 廠商如何讓設計者看到我的素材？\n素材管理上傳並選主分類。設計者在設計稿選相同分類即可看到。\n\n## 還有問題\n/contact.html',
     E'## How are credits counted?\n(Draft)\n\n## Empty vendor library?\nPick a main category first.\n\n## How do designers see my assets?\nUpload in vendor materials with a main category.')
) AS v(folder_slug, slug, title, title_en, summary, summary_en, sort_order, body, body_en)
JOIN public.help_guide_folders f ON f.slug = v.folder_slug
ON CONFLICT (folder_id, slug) DO NOTHING;

INSERT INTO public.payment_config (key, value, updated_at)
VALUES ('help_guides_draft_tree_20260903', '1', now())
ON CONFLICT (key) DO NOTHING;
