-- 操作介紹：人像生成風格定位文案（無流程／模型說明，混合取消 BETA）
-- 可重複執行。文案避免 ASCII 分號，以免後台 migration 以 ; 切句時被截斷。

UPDATE public.help_guide_pages p
SET
    summary = '清晰、氛圍、混合、寬鬆尺度。依擅長選風格：人像還原度、光影質感、均衡、貼身衣物。',
    summary_en = 'Clear, mood, hybrid, looser scale. Pick by strength: face fidelity, light and mood, balance, close-fit apparel.',
    blocks_json = $hg$[
        {"type":"text","sort":0,"text":"## 這是做什麼\n人像攝影可選**生成風格**（清晰／氛圍／混合／寬鬆尺度）。同一套主題、場景、攝影參數與衣著模式下，成品質感不同。\n\n總覽：[/help/promo-camera/portrait](/help/promo-camera/portrait)","text_en":"## What this is\nPortrait photography has **render styles** (clear / mood / hybrid / looser scale). Theme, scene, camera settings, and outfit mode stay the same. The look changes.\n\nOverview: [/help/promo-camera/portrait](/help/promo-camera/portrait)"},
        {"type":"text","sort":1,"text":"## 怎麼選\n- 人像還原度佳 → **清晰**\n- 光影質感佳 → **氛圍**\n- 人像與光影都要 → **混合**\n- 貼身衣物（內衣、泳裝等）→ **寬鬆尺度**（方案三／方案四，仍禁止裸露）","text_en":"## How to choose\n- Strong face fidelity → **Clear**\n- Strong light and mood → **Mood**\n- Balanced face and light → **Hybrid**\n- Close-fit apparel (lingerie, swimwear) → **Looser scale** (Plan 3 / Plan 4, nudity not allowed)"},
        {"type":"text","sort":2,"text":"## 人像通用原則\n下列原則適用**整個人像模式**：每種生成風格、三種衣著（依原圖／依場景／依描述）、有無描述、含證件／正式主題都一樣。選證件主題時姿勢依該主題（正面正式），不鎖原圖姿勢。\n\n- **忽略原圖姿勢**（不跟上傳圖的姿勢）\n- 依原圖：人物與服裝款式色系跟參考圖。依場景／依描述：只跟人物，衣服另依場景或描述\n- **貼身衣物**請用**寬鬆尺度**（方案三／方案四，免費與方案二不可用）\n- 清晰、氛圍、混合不適合貼身商品展示\n- 仍**禁止裸露**（內衣／泳裝可以，裸露不行）","text_en":"## Portrait-wide principles\nThese apply to **all of portrait mode**: every render style, every outfit mode (reference / scene / description), with or without a written description, including formal ID. Choosing the ID theme means pose follows that brief (front-facing, formal), not the uploaded pose.\n\n- **Ignore the original pose**\n- Reference outfit: person plus garment style and colors from the upload. Scene / description outfit: copy the person only\n- **Close-fit apparel** uses **Looser scale** (Plan 3 / Plan 4, not free or Plan 2)\n- Clear, mood, and hybrid are not for close-fit product shots\n- **Nudity is still not allowed** (lingerie / swimwear is fine)"},
        {"type":"text","sort":3,"text":"## 清晰\n- **擅長**：人像還原度佳\n- **適合**：要快、要穩、要像本人\n- **不適合**：貼身衣物（請用寬鬆尺度）","text_en":"## Clear\n- **Strength**: strong face fidelity\n- **Best for**: speed, stability, likeness to the reference\n- **Not for**: close-fit apparel (use Looser scale)"},
        {"type":"text","sort":4,"text":"## 氛圍\n- **擅長**：光影質感佳\n- **適合**：商業攝影感、人與場景融合自然\n- **不適合**：貼身衣物（請用寬鬆尺度）","text_en":"## Mood\n- **Strength**: strong light and mood\n- **Best for**: commercial still, person blended into the scene\n- **Not for**: close-fit apparel (use Looser scale)"},
        {"type":"text","sort":5,"text":"## 混合\n- **擅長**：人像與光影均衡\n- **適合**：構圖與氛圍都要\n- **不適合**：貼身衣物（請用寬鬆尺度）","text_en":"## Hybrid\n- **Strength**: balanced face and light\n- **Best for**: when you want both composition and mood\n- **Not for**: close-fit apparel (use Looser scale)"},
        {"type":"text","sort":6,"text":"## 寬鬆尺度\n- **擅長**：貼身衣物專用\n- **適合**：內衣、泳裝等貼身商品展示\n- **資格**：方案三／方案四\n- **禁止裸露**：內衣／泳裝可以，裸露不行\n- **不適合**：要高度像本人或證件（請用清晰）","text_en":"## Looser scale\n- **Strength**: close-fit apparel\n- **Best for**: lingerie, swimwear, and similar close-fit products\n- **Who**: Plan 3 / Plan 4 only\n- **No nudity**: lingerie / swimwear is fine, nudity is not\n- **Not for**: close likeness or ID photos (use Clear)"},
        {"type":"text","sort":7,"text":"## 衣著模式\n- **依原圖**：臉、身材與服裝都跟參考圖。\n- **依場景**：服裝依主題／場景決定。\n- **依描述**：服裝寫在描述欄（必填）。\n\n衣著本身就是產品（內衣、泳裝等）時，請用寬鬆尺度：人像參考用較清楚的身份照、另傳產品圖、衣著選「依描述」。仍禁止裸露。","text_en":"## Outfit modes\n- **From reference**: face, body, and garment follow the upload.\n- **From scene**: clothing follows theme and scene.\n- **From description**: clothing is written in the prompt (required).\n\nWhen the garment is the product (lingerie, swimwear), use Looser scale: a clear identity photo, a separate product image, and outfit from description. Nudity is still not allowed."},
        {"type":"text","sort":8,"text":"## 描述審核與外部擋圖\n人像生成會經過兩道審核。被擋時系統**不會改提示詞再送**，也不會自動改成依場景。仍禁止裸露。\n\n**描述審核（站內）**\n- 帳號可開「描述審核自動改寫」（個人帳號設定），只潤飾**你打的描述**。時裝／脫外套這類商業用語預設不改寫。硬擋與節流規則不變。\n- 頁面若寫「描述未通過安全審核」，就是這一關。\n\n**外部生圖審核**\n- 生圖服務會看參考圖＋場景＋描述整包。頁面出現「外部生圖審核未通過」就是這一關。\n- 同一張參考圖在客廳／戶外常可過、臥室被擋，是外部規則，不是站內又擋一次。\n- **清晰／氛圍／混合被擋**：貼身衣物請改用「寬鬆尺度」（方案三／方案四）。這三種風格不適合貼身商品。仍禁止裸露。系統不會改提示詞再送。\n- **已經在用寬鬆尺度仍被擋**：寬鬆尺度仍可能被外部擋。仍禁止裸露。請換較清楚的身份參考圖，或調整描述後再試。系統不會改提示詞再送。\n- 內衣／泳裝當產品時：身份照清楚、另傳產品圖、衣著選依描述、生成風格選寬鬆尺度。仍禁止裸露。\n\n外部規範（英文）：[Google 生成式 AI 禁止用途](https://policies.google.com/terms/generative-ai)、[圖像生成說明](https://ai.google.dev/gemini-api/docs/image-generation)、[圖像責任使用](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen)、[圖像使用政策](https://bfl.ai/legal/usage-policy)","text_en":"## Description review and external blocks\nPortrait generation goes through two reviews. A block is **not** retried with a changed prompt and does not auto-switch to scene outfit. Nudity is still not allowed.\n\n**On-site description review**\n- Account setting auto-polish descriptions only rewrites **your typed prompt**. Commercial fashion copy (including removing a coat) is usually left unchanged. Hard blocks and rate limits stay the same.\n- If the page says the description failed safety review, that is this step.\n\n**External image review**\n- The image API reviews the photo + scene + description together. External image generation review failed is this step.\n- The same photo may pass in a living room or outdoors and fail in a bedroom. That is the external rule, not a second site-side filter.\n- **Blocked in Clear / Mood / Hybrid**: for close-fit apparel, switch to **Looser scale** (Plan 3 / Plan 4). Those three styles are not for this. Nudity is still not allowed. The site does not rewrite the prompt and retry.\n- **Already on Looser scale and still blocked**: Looser scale can still fail external review. Nudity is still not allowed. Change to a clearer identity photo, or adjust the description. The site does not rewrite the prompt and retry.\n- If lingerie or swimwear is the product: use a clear identity photo, a separate product image, outfit from description, and Looser scale. Nudity is still not allowed.\n\nExternal policies: [Google Generative AI Prohibited Use](https://policies.google.com/terms/generative-ai), [Image generation](https://ai.google.dev/gemini-api/docs/image-generation), [Responsible AI for images](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen), [Image usage policy](https://bfl.ai/legal/usage-policy)"}
    ]$hg$::jsonb,
    updated_at = now()
FROM public.help_guide_folders f
WHERE p.folder_id = f.id
  AND f.slug = 'promo-camera'
  AND p.slug = 'portrait-modes';

INSERT INTO public.payment_config (key, value, updated_at)
VALUES ('help_guides_promo_portrait_render_style_copy_20260913', '1', now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
