-- 操作介紹草稿內文：每篇拆成「用途／操作／注意」等文字區塊
-- 英文欄位（title_en／summary_en／text_en）刻意留空，中文修正後再翻譯
-- 只更新尚未發佈的文章（不覆蓋你已公開或已改寫後發佈的內容）
-- 可重複執行。資料夾／篇 slug 須已存在（見 add-help-guides-draft-tree.sql）
-- 前台在發佈前仍不會出現；請到 /admin/operation-guides.html 檢視區塊後再公開

UPDATE public.help_guide_folders SET title_en = '', updated_at = now() WHERE is_published = false;

UPDATE public.help_guide_pages p
SET
    title_en = '',
    summary = v.summary,
    summary_en = '',
    blocks_json = v.blocks,
    updated_at = now()
FROM (
    VALUES
    ($hg$getting-started$hg$, $hg$overview$hg$, $hg$同一個 Email 帳號，沒有訂製者／製造商／供應商角色切換。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\nMatchDO 用**同一個登入帳號**完成設計、找廠商、上架素材。選單裡的 ① 訂製／設計、② 製造商、③ 產業供應商只是「我的功能」分區標題，方便找入口，**不是**三種身分、也不用切換角色。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 用 Google 或 Email 密碼登入（可並存在同一帳號）。\n2. 頂部「客製產品」進設計稿、版型、行銷影像與輔助工具。\n3. 「我的功能」看 ①②③ 全部入口（資格不足時頁面會說明，選單不會藏起來）。\n4. 方案與點數在「方案與定價」「我的點數」。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n全站只有兩項業務限制：免費帳號不能上傳**產品／素材**（展示案例除外）；沒有至少 1 件**展示中**作品，不能匯入產業供應商目錄。管理員與測試員不受限。\n\n相關：[/help/getting-started/login](/help/getting-started/login)、[/help/membership/free-limits](/help/membership/free-limits)","text_en":""}]$hg$::jsonb),
    ($hg$getting-started$hg$, $hg$login$hg$, $hg$Google 與 Email 密碼可並存在同一帳號；可設定密碼與忘記密碼。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n同一個 Email 可以同時用 **Google 登入** 和 **Email＋密碼**。之後用哪一種都能進同一個帳號、同一份點數與作品，不必另開身分。","text_en":""},{"type":"text","sort":1,"text":"## 用 Google 登入\n1. 點「使用 Google 登入」。\n2. 選要綁定的 Google 帳號。\n3. 第一次會建立 MatchDO 帳號；之後同一 Google 即登入。","text_en":""},{"type":"text","sort":2,"text":"## 用 Email 與密碼\n1. 輸入 Email 與密碼註冊或登入。\n2. 若此 Email 已用 Google 註冊，可在帳號設定裡**再設一組密碼**，兩種方式並存。\n3. 忘記密碼：登入頁「忘記密碼」→ 收信重設。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n請用你收得到信的 Email。重設連結有時效。登入後點數、設計稿、廠商資料都掛在這個帳號上。","text_en":""}]$hg$::jsonb),
    ($hg$getting-started$hg$, $hg$first-visit$hg$, $hg$建議先看設計稿或商攝，再決定要不要建立廠商資料。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n第一次進來不必一次把所有功能學完。依你現在要做的事選一條路即可。","text_en":""},{"type":"text","sort":1,"text":"## 想先出設計圖\n到「客製產品 → 設計稿」（`/custom-product.html`）。選分類、寫描述或帶入版型後生圖，再存到我的數位資產。\n\n詳細：[/help/design-draft/](/help/design-draft/)","text_en":""},{"type":"text","sort":2,"text":"## 想先做行銷影像\n- 場景合成：情境圖 `/promo-image/` → [/help/promo-image/](/help/promo-image/)\n- 拍攝模擬：商攝導演 `/promo-camera`（產品／空間／人像）→ [/help/promo-camera/](/help/promo-camera/)","text_en":""},{"type":"text","sort":3,"text":"## 想被設計者找到\n同一帳號即可。先建立廠商資料，再上傳至少 1 件**展示中**作品，然後在素材管理上傳版型（付費方案才能上傳產品／素材）。\n\n詳細：[/help/vendor-start/](/help/vendor-start/)","text_en":""}]$hg$::jsonb),
    ($hg$design-draft$hg$, $hg$overview$hg$, $hg$同一工作區兩種進法：無樣版（只靠描述／分類）與有樣版（帶入廠商或官方版型）。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n設計稿是訂製產品的**生圖工作區**：選分類、寫你要的成品，必要時加上參考圖或版型，再生成設計圖。列表與目錄不在這一頁。","text_en":""},{"type":"text","sort":1,"text":"## 無樣版怎麼做\n1. 開啟 `/custom-product.html`。\n2. 選主分類（必選）；有子分類時再選子分類。\n3. 用文字描述造型、材質、顏色、結構。\n4. 可加本機參考圖（見參考圖篇）。\n5. 按生成；點數以頁面上的數字為準。","text_en":""},{"type":"text","sort":2,"text":"## 有樣版怎麼做\n從「廠商版型」或「官方版型」列表點「用此款進行設計」，會帶著該版型進入同一工作區，再改描述或加參考圖後生圖。\n\n列表：[/help/design-draft/vendor-styles](/help/design-draft/vendor-styles)、[/help/design-draft/official-templates](/help/design-draft/official-templates)","text_en":""},{"type":"text","sort":3,"text":"## 注意\n設計稿只負責建立／編輯與生圖，不是官方版型或廠商版型的總目錄。生成後可存到我的數位資產，並選擇要不要出現在首頁靈感牆。","text_en":""}]$hg$::jsonb),
    ($hg$design-draft$hg$, $hg$references$hg$, $hg$本機上傳、廠商素材庫、官方版型，三種來源怎麼選。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n參考圖告訴生圖「長相與材質要朝哪裡靠」。來源有三種：你電腦上的圖、廠商素材庫、官方版型。","text_en":""},{"type":"text","sort":1,"text":"## 本機上傳\n在參考圖區按「＋」選檔。適合手繪、實拍、自己的稿。圖會跟著這次設計使用。","text_en":""},{"type":"text","sort":2,"text":"## 從廠商素材庫選擇\n1. **先選好主分類**（沒選分類會對不到廠商上傳的素材）。\n2. 點「從廠商素材庫選擇」。\n3. 點卡片加入參考；卡片上有廠商名稱，之後可連到該廠。\n若該分類尚無公開素材，會顯示尚無圖。","text_en":""},{"type":"text","sort":3,"text":"## 官方版型\n到獨立列表 `/official-templates/` 瀏覽後「用此款進行設計」，或在設計稿走官方版型入口。官方版型是平台共用範例，顯示名固定為「官方版型」。","text_en":""},{"type":"text","sort":4,"text":"## 注意\n廠商庫沒圖時，先確認主分類是否與廠商上傳時相同。相關：[/help/faq](/help/faq)","text_en":""}]$hg$::jsonb),
    ($hg$design-draft$hg$, $hg$vendor-styles$hg$, $hg$公開列表瀏覽廠商版型，再用此版型進入設計稿。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n廠商把數位原型公開後，你可在獨立列表挑選「用此款進行設計」。這是**真列表頁**，不是設計稿裡的分頁。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼瀏覽\n1. 打開 `/vendor-styles/`。\n2. 用主分類／子分類（與搜尋）縮小範圍。\n3. 卡片可看圖、廠商與「看可搭配」（有關聯材料／配件時）。","text_en":""},{"type":"text","sort":2,"text":"## 用此版型設計\n點「用此款進行設計」會進入設計稿並帶入該版型。之後仍可改描述、加參考圖再生成。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n也可改逛 [/help/design-draft/official-templates](/help/design-draft/official-templates)。廠商要出現在此列表，需在素材管理上傳並公開、且選對主分類。","text_en":""}]$hg$::jsonb),
    ($hg$design-draft$hg$, $hg$official-templates$hg$, $hg$公開列表瀏覽官方版型，再用此版型進入設計稿。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n官方版型是平台提供的共用數位原型／材料／配件範例，方便還沒有指定廠商時先設計。列表在獨立網址，不是設計稿分頁。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼瀏覽\n1. 打開 `/official-templates/`。\n2. 選分類與素材類型（預設看數位原型；也可切材料／配件或全部）。\n3. 有關聯時可「看可搭配」看產品樹。","text_en":""},{"type":"text","sort":2,"text":"## 用此版型設計\n原型按「用此款進行設計」；材料／配件多為「加入參考圖」。都會深鏈進設計稿並帶上分類。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n前台顯示名固定「官方版型」。管理員上傳在後台官方版型庫，一般設計者不進該後台。","text_en":""}]$hg$::jsonb),
    ($hg$design-draft$hg$, $hg$generate-and-save$hg$, $hg$生圖、存到我的數位資產，以及要不要出現在媒體牆。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n把目前工作區的描述、分類與參考圖送給生圖，完成後可存成你的數位資產，之後再設計、商攝或找廠商。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼生成\n1. 確認分類與描述（有樣版時先看版型是否已帶入）。\n2. 看按鈕旁的點數（無參考／有參考可能不同，**以當頁顯示為準**）。\n3. 點生成，等結果預覽。\n4. 不滿意可改描述或參考圖再生成。","text_en":""},{"type":"text","sort":2,"text":"## 存到我的數位資產\n生成後按儲存（或頁面上同等按鈕）。之後在 `/client/my-custom-products.html` 可再開來改、當參考、做情境圖或商攝。","text_en":""},{"type":"text","sort":3,"text":"## 不上媒體牆\n儲存或公開時可選擇不要出現在首頁靈感牆。不上牆的作品仍在我的數位資產。\n\n見 [/help/membership/hide-from-wall](/help/membership/hide-from-wall)","text_en":""}]$hg$::jsonb),
    ($hg$materials$hg$, $hg$overview$hg$, $hg$材料組合：用雙色或三色配比生成材料／色卡參考，再帶回設計稿。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n材料組合用來做出**材料表面／配色參考圖**（雙色或三色、可套配色範例），不是整件產品的結構設計。做好後可存進我的數位資產，再匯入設計稿當材料參考。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/client/material-dual-color.html`（客製產品 → 材料組合）。\n2. 選雙色或三色，調整主色／輔色與比重。\n3. 可開「配色範例」套用官方或你存過的組合。\n4. 生成（需登入與點數，以頁面為準）。\n5. 結果出現在「我的數位資產」的材料組合分頁。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n任何登入＋點數即可生成，不必先有廠商資料。設計稿可從資產庫把材料組合圖拉進材料槽。\n\n相關：[/help/my-assets/](/help/my-assets/)、[/help/design-draft/references](/help/design-draft/references)","text_en":""}]$hg$::jsonb),
    ($hg$print-asset$hg$, $hg$overview$hg$, $hg$印花：做出可印在產品表面的圖樣／印花稿。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n印花工具產出**表面圖樣／印花稿**，之後可當設計稿的表面印刷參考，而不是整件產品建模。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/client/print-asset.html`。\n2. 依頁面說明準備圖或描述。\n3. 生成後存到我的數位資產（印花分頁）。\n4. 回到設計稿，從資產庫或參考圖帶入。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n點數與可下載格式以該頁顯示為準。請使用你有權使用的圖樣，避免侵權素材。","text_en":""}]$hg$::jsonb),
    ($hg$promo-image$hg$, $hg$overview$hg$, $hg$情境圖：把產品放進場景的行銷圖。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n情境圖把**已有的產品圖**放進使用場景（生活、陳列、空間），做出行銷用圖。偏「場景合成」，不是商攝導演那種拍攝參數模擬。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/promo-image/`。\n2. 選或上傳產品圖（可從數位資產帶入）。\n3. 選場景／情境後生成。\n4. 結果可進我的數位資產「情境圖」分頁。","text_en":""},{"type":"text","sort":2,"text":"## 與商攝導演的差別\n- **情境圖**：現成產品圖 × 場景。\n- **商攝導演**：產品／空間／人像的拍攝模擬（燈光、鏡頭、空間地圖等）。\n\n商攝說明：[/help/promo-camera/](/help/promo-camera/)","text_en":""}]$hg$::jsonb),
    ($hg$promo-camera$hg$, $hg$overview$hg$, $hg$商攝導演三種模式：產品、空間、人像。官網與手機 App 共用帳號與點數。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n商攝導演用來**模擬商業攝影**：先選模式，再調拍攝條件後出圖。適合已有產品或空間概念、要行銷視覺時。","text_en":""},{"type":"text","sort":1,"text":"## 三種模式\n- 產品攝影：單件或一組產品的棚拍／情境拍 → [/help/promo-camera/product](/help/promo-camera/product)\n- 空間攝影：平面配置 → 空間地圖 → 標記 → 平視 → [/help/promo-camera/space](/help/promo-camera/space)\n- 人像攝影：人物與服裝／場景 → [/help/promo-camera/portrait](/help/promo-camera/portrait)","text_en":""},{"type":"text","sort":2,"text":"## 怎麼進入\n- 官網：`/promo-camera`（選單與頭像也可進）\n- 手機網頁 App：`/promo-camera-app`（同一帳號、同一點數）→ [/help/promo-camera/pwa-app](/help/promo-camera/pwa-app)\n- 設計稿也可嵌入商攝（手機與桌面入口不同，功能同一套點數）","text_en":""},{"type":"text","sort":3,"text":"## 注意\n點數與解析度（含 2K／4K）一律以**當頁顯示**為準。生成前看預扣點數。","text_en":""}]$hg$::jsonb),
    ($hg$promo-camera$hg$, $hg$product$hg$, $hg$商攝導演：產品攝影模式。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n產品模式用來拍「商品照」：白底、情境、多角度等，適合已有產品外觀、要上架或社群圖時。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/promo-camera`，切到**產品**。\n2. 上傳或選產品圖（可從設計稿／資產帶入）。\n3. 調場景、光線、鏡頭等規格（左欄可收折）。\n4. 看點數後按生成。\n5. 結果可下載或留在商攝紀錄，再帶進其他工具。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n解析度與點數以頁面為準。產品圖越清楚、裁切越乾淨，通常越穩。","text_en":""}]$hg$::jsonb),
    ($hg$promo-camera$hg$, $hg$space$hg$, $hg$平面配置 → 空間地圖 → 地圖標記 → 平視攝影。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n空間模式從**平面配置**做出空間感，再在地圖上標記要拍的位置，最後出平視照片。適合展場、店舖、室內陳列。","text_en":""},{"type":"text","sort":1,"text":"## 平面配置與空間地圖\n1. 切到**空間**模式。\n2. 上傳或描述平面／格局。\n3. 生成或確認**空間地圖**（俯視配置）。\n4. 地圖上用 A–Z 標記要強調的位置。","text_en":""},{"type":"text","sort":2,"text":"## 平視攝影\n標記完成後，選要拍的區域或視角，再出**平視**圖。右側相機會保留，用來理解鏡頭方向。點數（含 2K／4K）以頁面為準。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n請依頁面上的步驟走完「地圖 → 標記 → 平視」，不要跳過標記就期待對到特定角落。","text_en":""}]$hg$::jsonb),
    ($hg$promo-camera$hg$, $hg$portrait$hg$, $hg$商攝導演：人像攝影模式。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n人像模式模擬人物在場景中的商業人像／穿戴照，適合服裝、配件上身、形象圖。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. `/promo-camera` 切到**人像**。\n2. 上傳人物參考（體型／臉部依頁面欄位）。\n3. 補場景、服裝或產品說明。\n4. 看點數後生成。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n請使用你有權使用的人像。解析度與點數以頁面為準。","text_en":""}]$hg$::jsonb),
    ($hg$promo-camera$hg$, $hg$pwa-app$hg$, $hg$線上 PWA 與官網同一帳號、同一點數。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n`/promo-camera-app` 是商攝的**手機網頁 App**：同一套登入與點數，介面依手機操作調整，不是整站搬進手機。","text_en":""},{"type":"text","sort":1,"text":"## 與官網的關係\n- 帳號、點數、生成紀錄與官網 `/promo-camera` 共用。\n- 三種模式（產品／空間／人像）都在。\n- 設計稿在手機嵌入商攝時，也可能走這個 App 殼。","text_en":""},{"type":"text","sort":2,"text":"## 如何加到手機主畫面\n用手機瀏覽器打開 `/promo-camera-app`。\n- **iPhone**：用 Safari → 分享 → 加入主畫面。其他瀏覽器請改用 Safari。\n- **Android**：若出現安裝提示就加入；或用瀏覽器選單「加到主畫面」。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n這是瀏覽器 App，不是另一個帳號。請用同一個 MatchDO 登入。","text_en":""}]$hg$::jsonb),
    ($hg$pattern-extract$hg$, $hg$overview$hg$, $hg$圖樣提取：從數位資產選圖提取圖樣（避免侵權，不從任意上傳圖）。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n從**你已經存在數位資產裡的圖**抽出可重複的圖樣（花紋、印花單元），再拿去印花或當參考。不能從任意網圖直接抽，以降低侵權風險。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/pattern-extract/`。\n2. 從數位資產選一張圖（沒有資產請先在設計稿或印花產出並儲存）。\n3. 依頁面設定範圍／解析度後提取。\n4. 結果可下載或回到資產／設計使用。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n點數與輸出尺寸以該頁為準。請只提取你有權使用的圖案。","text_en":""}]$hg$::jsonb),
    ($hg$design-to-physical$hg$, $hg$overview$hg$, $hg$寫實化：把設計稿或圖稿轉成更接近實物拍攝的影像。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n寫實化把**產品圖稿／示意圖**變成較接近實拍的成品照。適合草圖、平面設計已定、要給客戶看「實物感」時。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/design-to-physical/`，或在設計區切「寫實化」。\n2. 選本機圖或數位資產裡的圖。\n3. 可加簡短說明後執行。\n4. 廠商素材庫的原型／配件也可在編輯圖庫做寫實化（點數可能不同，以頁面為準）。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n**本機原稿再跑一次，通常比對已上架、已壓縮的圖再跑效果好。** 不要對寫實化結果反覆再寫實化。點數以頁面為準（設計區與廠商圖庫可能不同）。","text_en":""}]$hg$::jsonb),
    ($hg$scene-sim$hg$, $hg$overview$hg$, $hg$實境模擬：把設計放到真實場景或人物環境。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n實境模擬把**產品圖**套進你提供的環境或人物照片，看實際配色與比例。和情境圖不同：這裡通常由你指定真實參考場景。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/scene-sim/`。\n2. 選產品圖（常從數位資產）。\n3. 上傳環境或人物參考。\n4. 生成；點數以頁面為準。\n5. 若未下載／未另存，有些結果不會進數位資產（以該頁說明為準）。","text_en":""},{"type":"text","sort":2,"text":"## 與情境圖的差別\n情境圖偏平台場景模板；實境模擬偏「我這張現場／這個人」。行銷場景合成見 [/help/promo-image/](/help/promo-image/)。","text_en":""}]$hg$::jsonb),
    ($hg$my-assets$hg$, $hg$overview$hg$, $hg$我的數位資產：設計稿與生成結果的收藏處。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n這裡集中你存過的設計圖、材料組合、印花、情境圖等，方便再開、當參考、做商攝或找廠商。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/client/my-custom-products.html`。\n2. 用分頁切設計圖／材料組合／情境圖等。\n3. 點卡片可再設計、看履歷、或帶去其他工具。\n4. 設計風向結果也可切「設計風向」檢視。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n不上媒體牆的作品仍會列在這裡。刪除前請確認沒有還要再用的衍生圖。","text_en":""}]$hg$::jsonb),
    ($hg$gallery$hg$, $hg$overview$hg$, $hg$圖庫找廠商：從作品／圖庫找到製作方。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n從公開作品、對照圖、系列圖瀏覽，點進廠商公開頁或繼續設計。適合「先看成品再決定找誰做」。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/custom/gallery.html` 或首頁靈感牆。\n2. 用分類或類型篩選。\n3. 點作品看大圖；有廠商則進公開首頁。\n4. 可再從廠商頁「用此廠商版型設計」回設計稿。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n靈感牆是公開內容；你自己不上牆的作品不會出現在這裡。","text_en":""}]$hg$::jsonb),
    ($hg$design-direction$hg$, $hg$overview$hg$, $hg$設計風向（測試中）：意圖分析、我的設計風向、找製作方。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n設計風向把「我想做什麼」整理成可保存的方向，再拿去找製作方。此區標示**測試中**，介面可能再調整。","text_en":""},{"type":"text","sort":1,"text":"## 入口\n頂部「設計風向」：\n- 設計意圖分析 → [/help/design-direction/intent](/help/design-direction/intent)\n- 我的設計風向 → [/help/design-direction/my-direction](/help/design-direction/my-direction)\n- 找製作方 → [/help/design-direction/find-makers](/help/design-direction/find-makers)","text_en":""},{"type":"text","sort":2,"text":"## 注意\n測試中功能以頁面實際按鈕為準。一般設計生圖仍走設計稿。","text_en":""}]$hg$::jsonb),
    ($hg$design-direction$hg$, $hg$intent$hg$, $hg$描述或上傳後分析設計意圖。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n用文字或圖，讓系統整理這次設計的品類、風格與重點，方便之後對照或找製作方。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開設計意圖分析頁（設計風向選單）。\n2. 填描述或上傳參考。\n3. 送出後閱讀分析結果。\n4. 可存成「我的設計風向」。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n結果是分析摘要，不會自動變成一張設計稿。要生圖請到設計稿。","text_en":""}]$hg$::jsonb),
    ($hg$design-direction$hg$, $hg$my-direction$hg$, $hg$已存的設計風向結果。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n查看你存過的設計風向，避免每次重填意圖。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n從設計風向選單進「我的設計風向」，或在我的數位資產切到設計風向檢視。點一筆可再看內容或接著找製作方。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n與一般設計圖分頁不同，這裡存的是「方向」不是每一張生圖。","text_en":""}]$hg$::jsonb),
    ($hg$design-direction$hg$, $hg$find-makers$hg$, $hg$依設計風向找製作方。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n帶著已整理的設計方向，瀏覽可能接單的製作方。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/client/find-makers.html`。\n2. 選一筆設計風向或依頁面篩選。\n3. 點進廠商公開頁或留下詢價（依該頁按鈕）。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n沒有風向也可以先逛圖庫找廠商：[/help/gallery/](/help/gallery/)","text_en":""}]$hg$::jsonb),
    ($hg$vendor-start$hg$, $hg$overview$hg$, $hg$建立廠商資料、進入控制台。同一帳號即可，不必另開角色。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n把同一帳號補上**製造商資料**後，就能上傳展示案例、素材，並有公開首頁給設計者看。不是換成另一種帳號。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 「我的功能 → ②」進廠商控制台 `/client/manufacturer-dashboard.html`。\n2. 依提示建立或補齊廠商名稱、介紹、聯絡與 LOGO。\n3. 控制台可進：展示案例、素材管理、詢價、公開首頁預覽。","text_en":""},{"type":"text","sort":2,"text":"## 免費帳號能做什麼\n展示案例可以上傳。**產品／素材**（版型、材料、零件、供應商目錄）上傳需要付費方案。\n\n見 [/help/membership/free-limits](/help/membership/free-limits)","text_en":""}]$hg$::jsonb),
    ($hg$vendor-portfolio$hg$, $hg$overview$hg$, $hg$展示案例：系列圖與對照圖。同一頁兩種作品形態。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n展示案例是給設計者看的**實績**，也是解鎖「匯入產業供應商目錄」的條件（至少 1 件展示中）。免費帳號也可以傳。","text_en":""},{"type":"text","sort":1,"text":"## 系列圖\n同一作品多張圖（不同角度或細節）。在 `/client/manufacturer-portfolio.html` 新增作品，選系列圖並填名稱、分類、亮點。","text_en":""},{"type":"text","sort":2,"text":"## 對照圖\n改前／改後或設計／成品對照。同一頁選擇對照形態上傳兩側圖片。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n請把要給外人看的案例設為**展示中／公開**。未展示的不算「至少 1 件」門檻。","text_en":""}]$hg$::jsonb),
    ($hg$vendor-materials$hg$, $hg$overview$hg$, $hg$素材管理：產品版型、材料版型、零件版型。同一頁不同類型。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n上傳設計者在設計稿「廠商素材庫」會看到的**數位原型、材料、配件**。選對主分類，對方選同一分類才看得到。","text_en":""},{"type":"text","sort":1,"text":"## 產品版型（數位原型）\n結構／造型主體。建議選子分類、補標題與圖（封面＋圖庫）。可關聯材料與配件，讓設計者「看可搭配」。","text_en":""},{"type":"text","sort":2,"text":"## 材料與零件版型\n材料：表面、色、質感參考。零件：五金、提把等可搭配件。同一頁切類型上傳。","text_en":""},{"type":"text","sort":3,"text":"## 怎麼操作\n1. `/client/manufacturer-materials.html`\n2. 選類型 → **主分類必選** → 標題與圖片。\n3. 公開後，設計者在設計稿選相同主分類即可在庫裡看到。","text_en":""},{"type":"text","sort":4,"text":"## 注意\n免費方案不能上傳素材。見 [/help/membership/free-limits](/help/membership/free-limits)。這頁不是供應商目錄上架（那是 ③）。","text_en":""}]$hg$::jsonb),
    ($hg$vendor-embed$hg$, $hg$overview$hg$, $hg$把模擬／選版型嵌到外站。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n用 iframe 把 MatchDO 的選版型／模擬放進你自己的官網，訪客不必先學會整站。這不是設計稿的一個分頁。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 在廠商相關設定或 Embed 說明頁取得嵌入碼（含 embed id）。\n2. 把 iframe 貼到外站。\n3. 可用主題／外框參數（若頁面有提供）。\n4. 訪客操作紀錄可在站內 Embed 設計紀錄查看（若已開）。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n嵌入頁與官網設計稿網址不同，請複製後台提供的網址，不要自己改成 `custom-product.html?tab=`。","text_en":""}]$hg$::jsonb),
    ($hg$vendor-inquiries$hg$, $hg$overview$hg$, $hg$查看設計者傳來的詢價。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n設計者對你的作品或版型留下詢價後，在這裡集中看需求與聯絡。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 廠商控制台 → 詢價，或「我的功能 → ②」詢價列表。\n2. 點一筆看需求說明與對方聯絡方式。\n3. 依頁面上的回覆或站外聯絡方式處理。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n公開首頁與素材越完整，詢價越容易對到正確品類。","text_en":""}]$hg$::jsonb),
    ($hg$vendor-profile$hg$, $hg$overview$hg$, $hg$廠商公開首頁（可被搜尋），不是後台控制台。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n`/vendor-profile.html?id=…` 是給設計者與搜尋引擎看的**公開店面**。控制台只有你登入後看得到。","text_en":""},{"type":"text","sort":1,"text":"## 公開頁與後台的差別\n- 公開頁：介紹、作品、可引用的版型入口。\n- 控制台：上傳、詢價、設定、未公開內容。","text_en":""},{"type":"text","sort":2,"text":"## 如何分享\n在控制台或「我的功能 → 我的廠商公開首頁」複製連結。可放在名片、IG 或詢價回覆。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n公開頁可被收錄；後台 `/client/manufacturer-dashboard.html` 不會當公開店面。","text_en":""}]$hg$::jsonb),
    ($hg$vendor-sourcing$hg$, $hg$overview$hg$, $hg$上游採購（B 線）：瀏覽產業供應商目錄並匯入到自己的素材庫。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n製造商向**產業供應商目錄**引用產品／材料，匯入後出現在你可管理的庫裡，再視需要轉成給設計者看的素材。這是 B 線，不是你自己拍的展示案例。","text_en":""},{"type":"text","sort":1,"text":"## 匯入條件\n同一帳號須已有至少 **1 件展示中作品**。選單上仍看得到入口；條件不足時頁面會說明。","text_en":""},{"type":"text","sort":2,"text":"## 怎麼操作\n1. 我的功能 → ② → 上游採購／產業供應商目錄。\n2. 瀏覽供應商與品項。\n3. 匯入到已匯入上游品項。\n4. 再依你的流程整理或上架給設計者（若產品要求另一步）。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n免費不能上傳自己的素材，但匯入還看展示案例門檻。種子／平台代管廠商另有規則。","text_en":""}]$hg$::jsonb),
    ($hg$supplier-catalog$hg$, $hg$overview$hg$, $hg$產業供應商上架數位產品庫（產品／材料）。與廠商素材管理是不同頁。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n③ **產業供應商**把可被製造商匯入的產品／材料目錄上架。這不是 ② 素材管理（那是製造商給設計者的版型庫）。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼上架\n1. 我的功能 → ③ → 上架數位產品庫。\n2. 新增產品或材料，補名稱、圖、規格（依表單）。\n3. 儲存後，製造商可在上游採購看到（其須符合展示案例條件）。","text_en":""},{"type":"text","sort":2,"text":"## 注意\n免費帳號不能上傳目錄品項。見 [/help/membership/free-limits](/help/membership/free-limits)","text_en":""}]$hg$::jsonb),
    ($hg$supplier-profile$hg$, $hg$overview$hg$, $hg$供應商公開頁，以及製造商引用紀錄。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n供應商也有公開頁，讓製造商認識你的目錄；「製造商引用紀錄」看誰匯入過你的品項。","text_en":""},{"type":"text","sort":1,"text":"## 公開頁\n從我的功能 → ③ → 供應商公開首頁進入或複製連結。內容來自你上架的目錄與基本資料。","text_en":""},{"type":"text","sort":2,"text":"## 製造商引用紀錄\n同一區查看哪些製造商匯入了哪些品項，方便後續業務聯絡。","text_en":""},{"type":"text","sort":3,"text":"## 注意\n公開頁與後台上架頁不同；不要把後台網址當成對外名片。","text_en":""}]$hg$::jsonb),
    ($hg$membership$hg$, $hg$overview$hg$, $hg$訂閱方案的每月點數，與單次儲值不同。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n付費訂閱每月給一包點數，用來生圖、商攝、寫實化等。單次儲值是另外買點，不取代訂閱的方案權益（例如上傳素材）。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼看方案\n1. `/subscription-plans.html` 看各方案。\n2. `/credits.html` 看餘額、到期與儲值。\n3. 各工具按鈕旁的數字是**該次**預扣，以當頁為準。","text_en":""},{"type":"text","sort":2,"text":"## 相關\n- 儲值：[/help/membership/top-up](/help/membership/top-up)\n- 免費限制：[/help/membership/free-limits](/help/membership/free-limits)\n- 點數 FAQ：[/help/faq](/help/faq)","text_en":""}]$hg$::jsonb),
    ($hg$membership$hg$, $hg$top-up$hg$, $hg$單次儲值點數，與訂閱每月贈點分開看。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n點數不夠、或不想改方案時，在「我的點數」一次買入點數。這與訂閱每月發放是分開的兩本帳。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n1. 打開 `/credits.html`。\n2. 選儲值點數（快捷金額以頁面為準）。\n3. 依結帳方式完成付款。\n4. 成功後餘額更新，即可回工具繼續生成。","text_en":""},{"type":"text","sort":2,"text":"## 和訂閱的差別\n訂閱：每月給點，並可能包含上傳產品／素材等權益。儲值：只加點，**不會**把免費帳號變成可上傳素材。","text_en":""}]$hg$::jsonb),
    ($hg$membership$hg$, $hg$hide-from-wall$hg$, $hg$生成或公開時選擇不要出現在首頁靈感牆。$hg$, $hg$[{"type":"text","sort":0,"text":"## 這是做什麼\n不想讓這張設計出現在首頁靈感牆或公開圖庫時，在儲存／公開選項勾「不上媒體牆」。","text_en":""},{"type":"text","sort":1,"text":"## 怎麼操作\n在設計稿儲存（或該工具同等的公開選項）取消展示／勾不上牆。之後仍可在我的數位資產找到。","text_en":""},{"type":"text","sort":2,"text":"## 不上牆還會在哪裡\n我的數位資產、你自己的登入狀態。其他人在靈感牆看不到。","text_en":""}]$hg$::jsonb),
    ($hg$membership$hg$, $hg$free-limits$hg$, $hg$免費不可上傳產品與素材；展示案例仍可上傳。$hg$, $hg$[{"type":"text","sort":0,"text":"## 不能上傳什麼\n- 製造商**素材**（數位原型／材料／配件，`vendor_assets`）\n- 供應商**目錄品項**（`supplier_catalog_items`）\n頁面上傳鈕會停用，API 會說明原因。","text_en":""},{"type":"text","sort":1,"text":"## 仍可以做什麼\n- 上傳**展示案例**（也是之後匯入供應商目錄的條件）\n- 用點數做設計稿、商攝、情境圖等（有點就能做）\n- 瀏覽說明、版型列表、圖庫","text_en":""},{"type":"text","sort":2,"text":"## 管理員／測試員\n不受這兩項限制。一般會員請改訂閱方案後再上傳產品與素材。","text_en":""}]$hg$::jsonb),
    ($hg$faq$hg$, $hg$overview$hg$, $hg$點數、素材庫沒圖、如何讓設計者看到素材。$hg$, $hg$[{"type":"text","sort":0,"text":"## 點數怎麼算？\n每個生成按鈕旁會寫本次要扣多少。設計稿「無參考／有參考」、商攝解析度、寫實化入口（設計區或廠商圖庫）可能不同。**請以該頁數字為準**，不要背舊表。餘額在 `/credits.html`，方案在 `/subscription-plans.html`。","text_en":""},{"type":"text","sort":1,"text":"## 從廠商素材庫選擇時沒有圖？\n1. 設計稿是否已選**主分類**。\n2. 該分類是否有廠商公開上傳。\n3. 廠商上傳時的主分類是否與你現在選的相同（分類搬家後，舊資料可能還掛在舊分類）。\n沒有素材時會提示尚無圖，可改分類或改用本機圖／官方版型。","text_en":""},{"type":"text","sort":2,"text":"## 廠商如何讓設計者看到我的素材？\n在素材管理上傳，**主分類必選**，並設為公開。設計者在設計稿選相同主分類，打開「從廠商素材庫選擇」即可看到。免費帳號需先訂閱才能上傳素材。","text_en":""},{"type":"text","sort":3,"text":"## 還有問題\n聯絡我們：`/contact.html`。操作介紹目錄：[/help/](/help/)","text_en":""}]$hg$::jsonb)
) AS v(folder_slug, slug, summary, blocks)
JOIN public.help_guide_folders f ON f.slug = v.folder_slug
WHERE p.folder_id = f.id
  AND p.slug = v.slug
  AND p.is_published = false;

INSERT INTO public.payment_config (key, value, updated_at)
VALUES ('help_guides_draft_content_20260903', '1', now())
ON CONFLICT (key) DO NOTHING;
