-- 操作介紹：寬鬆尺度（大尺度產品．方案三／方案四．每分鐘上限）
-- 可重複執行。文案避免 ASCII 分號，以免後台 migration 以 ; 切句時被截斷。
-- 前台／操作介紹不寫模型名稱。

UPDATE public.help_guide_pages p
SET
    title = '人像生成風格',
    title_en = 'Portrait render styles',
    summary = '清晰、氛圍、混合、寬鬆尺度。寬鬆尺度給大尺度產品用，限方案三／方案四。',
    summary_en = 'Clear, mood, hybrid, and looser scale. Looser scale is for revealing products. Plan 3 / Plan 4 only.',
    is_published = true,
    blocks_json = $hg$[
        {"type":"text","sort":0,"text":"## 這是做什麼\n人像攝影可選**生成風格**（清晰／氛圍／混合／寬鬆尺度）。同一套主題、場景、攝影參數與衣著模式下，流程與成品質感不同。\n\n總覽：[/help/promo-camera/portrait](/help/promo-camera/portrait)","text_en":"## What this is\nPortrait photography has **render styles** (clear / mood / hybrid / looser scale). Theme, scene, camera settings, and outfit mode stay the same. The pipeline and look change.\n\nOverview: [/help/promo-camera/portrait](/help/promo-camera/portrait)"},
        {"type":"text","sort":1,"text":"## 人像通用生圖原則\n下列原則適用**整個人像模式**：每種生成風格、三種衣著（依原圖／依場景／依描述）、有沒有填描述、含證件／正式主題都一樣。選證件主題時姿勢依該主題（正面正式），不鎖原圖姿勢。\n\n- **忽略原圖姿勢**（不跟上傳圖的姿勢）\n- 依原圖：人物與服裝款式色系跟參考圖。依場景／依描述：只跟人物，衣服另依場景或描述\n- **大尺度產品**請用**寬鬆尺度**（方案三／方案四，免費與方案二不可用）\n- 清晰、氛圍、混合不適合大尺度產品\n\n畫面說明不會送給生圖模型。原則是後端寫進提示詞的。","text_en":"## Portrait-wide generation principles\nThese apply to **all of portrait mode**: every render style, every outfit mode (reference / scene / description), with or without a written description, including formal ID. Choosing the ID theme means pose follows that brief (front-facing, formal), not the uploaded pose.\n\n- **Ignore the original pose**\n- Reference outfit: person plus garment style and colors from the upload. Scene / description outfit: copy the person only\n- **Revealing products** use **Looser scale** (Plan 3 / Plan 4, not free or Plan 2)\n- Clear, mood, and hybrid are not for revealing products\n\nOn-screen hints are not sent to the image model. The backend writes these into the prompt."},
        {"type":"text","sort":2,"text":"## 清晰\n- **流程**：一次出圖。\n- **適合**：要快、要穩、要臉較像參考圖本人。\n- **不適合**：大尺度產品（內衣、泳裝等）。那種請用寬鬆尺度。","text_en":"## Clear\n- **Pipeline**: one image pass.\n- **Best for**: speed, a clear reference, and a closer face match.\n- **Not for**: revealing products (lingerie, swimwear). Use Looser scale for those."},
        {"type":"text","sort":3,"text":"## 氛圍\n- **流程**：草稿（人與場景一起畫）→ 氛圍重拍（統一光影與質感）。\n- **適合**：要商業攝影感、人與場景融合較自然。\n- **不適合**：大尺度產品。那種請用寬鬆尺度。\n- **管理員**：可對照「草稿繪製」與「氛圍圖」（一般使用者只看成品）。","text_en":"## Mood\n- **Pipeline**: draft (person and scene together) then look restyle (unified light and texture).\n- **Best for**: a commercial still, with the person blended into the scene.\n- **Not for**: revealing products. Use Looser scale for those.\n- **Admins**: can compare draft vs look (everyone else sees the final still)."},
        {"type":"text","sort":4,"text":"## 混合（BETA）\n- **流程**：文生空景（沒有人）→ 放入人物 → 氛圍重拍。\n- **適合**：想先鎖定空景構圖與光線，再把人融進去。\n- **不適合**：大尺度產品。那種請用寬鬆尺度。\n- **管理員**：可對照「場景底圖」與「成品」。混合仍在優化，請與氛圍對照挑選。","text_en":"## Hybrid (BETA)\n- **Pipeline**: empty scene, then place the person, then look restyle.\n- **Best for**: locking environment and light first, then integrating the person.\n- **Not for**: revealing products. Use Looser scale for those.\n- **Admins**: can compare empty scene vs final still. Hybrid is still being refined. Compare with mood."},
        {"type":"text","sort":5,"text":"## 寬鬆尺度\n- **用途**：給**大尺度產品**用（內衣、泳裝等）。清晰／氛圍／混合不適合這類產品。\n- **資格**：限**方案三、方案四**會員。免費與方案二不可用。管理員與測試員不受限。\n- **頻率**：每個帳號每分鐘有生圖次數上限（後台可設）。套圖一次算多張。\n- **流程**：與清晰同一套提示詞，一次出圖。解析度為 1／4 MP。\n- **點數**：1 MP 與 4 MP 各有獨立價格，不套方案三／四的每張少 5 點。以頁面顯示為準。\n- **臉部複製程度較低**，成品較不像原圖本人。\n- **不適合**：要高度像本人、證件或認臉。那種請用清晰。","text_en":"## Looser scale\n- **Use**: for **revealing products** (lingerie, swimwear). Clear / mood / hybrid are not for this.\n- **Who**: **Plan 3 and Plan 4** members only. Free and Plan 2 cannot use it. Staff are not gated.\n- **Rate**: each account has a per-minute generation cap (set in admin). A batch counts as multiple shots.\n- **Pipeline**: the same prompt as Clear, one image pass. Resolution is 1 / 4 MP.\n- **Credits**: 1 MP and 4 MP have separate prices. Plan 3/4 per-shot minus 5 does not apply. Trust the page.\n- **Face match is looser**, so the result looks less like the uploaded person.\n- **Not for**: close likeness, ID photos, or face recognition. Use Clear for those."},
        {"type":"text","sort":6,"text":"## 衣著模式\n- **依原圖**：臉、身材與服裝都跟參考圖（寬鬆尺度臉仍會比較不像）。\n- **依場景**：服裝依主題／場景決定。\n- **依描述**：服裝寫在描述欄（必填）。\n\n衣著本身就是產品（內衣、泳裝等）時，請用寬鬆尺度：人像參考用較清楚的身份照、另傳產品圖、衣著選「依描述」。","text_en":"## Outfit modes\n- **From reference**: face, body, and garment follow the upload (looser scale still copies the face less closely).\n- **From scene**: clothing follows theme and scene.\n- **From description**: clothing is written in the prompt (required).\n\nWhen the garment is the product (lingerie, swimwear), use Looser scale: a clear identity photo, a separate product image, and outfit from description."},
        {"type":"text","sort":7,"text":"## 描述審核與外部擋圖\n人像生成會經過兩道審核。被擋時系統**不會改提示詞再送**，也不會自動改成依場景。\n\n**描述審核（站內）**\n- 帳號可開「描述審核自動改寫」（個人帳號設定），只潤飾**你打的描述**。時裝／脫外套這類商業用語預設不改寫。硬擋與節流規則不變。\n- 頁面若寫「描述未通過安全審核」，就是這一關。\n\n**外部生圖審核**\n- 生圖服務會看參考圖＋場景＋描述整包。頁面出現「外部生圖審核未通過」就是這一關。\n- 同一張參考圖在客廳／戶外常可過、臥室被擋，是外部規則，不是站內又擋一次。\n- **清晰／氛圍／混合被擋**：大尺度產品請改用「寬鬆尺度」（方案三／方案四）。這三種風格不適合大尺度。系統不會改提示詞再送。\n- **已經在用寬鬆尺度仍被擋**：寬鬆尺度仍可能被外部擋。請換較清楚的身份參考圖，或調整描述後再試。每個帳號每分鐘有次數上限。系統不會改提示詞再送。\n- 內衣／泳裝當產品時：身份照清楚、另傳產品圖、衣著選依描述、生成風格選寬鬆尺度。\n\n外部規範（英文）：[Google 生成式 AI 禁止用途](https://policies.google.com/terms/generative-ai)、[圖像生成說明](https://ai.google.dev/gemini-api/docs/image-generation)、[圖像責任使用](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen)、[圖像使用政策](https://bfl.ai/legal/usage-policy)","text_en":"## Description review and external blocks\nPortrait generation goes through two reviews. A block is **not** retried with a changed prompt and does not auto-switch to scene outfit.\n\n**On-site description review**\n- Account setting auto-polish descriptions only rewrites **your typed prompt**. Commercial fashion copy (including removing a coat) is usually left unchanged. Hard blocks and rate limits stay the same.\n- If the page says the description failed safety review, that is this step.\n\n**External image review**\n- The image API reviews the photo + scene + description together. External image generation review failed is this step.\n- The same photo may pass in a living room or outdoors and fail in a bedroom. That is the external rule, not a second site-side filter.\n- **Blocked in Clear / Mood / Hybrid**: for revealing products, switch to **Looser scale** (Plan 3 / Plan 4). Those three styles are not for this. The site does not rewrite the prompt and retry.\n- **Already on Looser scale and still blocked**: Looser scale can still fail external review. Change to a clearer identity photo, or adjust the description. Each account has a per-minute cap. The site does not rewrite the prompt and retry.\n- If lingerie or swimwear is the product: use a clear identity photo, a separate product image, outfit from description, and Looser scale.\n\nExternal policies: [Google Generative AI Prohibited Use](https://policies.google.com/terms/generative-ai), [Image generation](https://ai.google.dev/gemini-api/docs/image-generation), [Responsible AI for images](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen), [Image usage policy](https://bfl.ai/legal/usage-policy)"}
    ]$hg$::jsonb,
    updated_at = now()
FROM public.help_guide_folders f
WHERE p.folder_id = f.id
  AND f.slug = 'promo-camera'
  AND p.slug = 'portrait-modes';

UPDATE public.help_guide_pages p
SET
    summary = '商攝導演：人像攝影（清晰／氛圍／混合／寬鬆尺度）。',
    summary_en = 'Promo camera: portrait mode (clear / mood / hybrid / looser scale).',
    blocks_json = $hg$[
        {"type":"text","sort":0,"text":"## 這是做什麼\n人像模式模擬人物在場景中的商業人像／穿戴照，適合服裝、配件上身、形象圖。","text_en":"## What this is\nPortrait mode places a person in a commercial still or wear-shot. Use it for apparel, accessories on-body, and lookbook images."},
        {"type":"text","sort":1,"text":"## 怎麼操作\n1. `/promo-camera` 切到**人像**。\n2. 上傳人物參考。\n3. 選**拍攝主題**與場景。可選產品圖、場景參考圖。\n4. 選**生成風格**：清晰／氛圍／混合／寬鬆尺度（詳見 [/help/promo-camera/portrait-modes](/help/promo-camera/portrait-modes)）。大尺度產品請用寬鬆尺度（方案三／方案四）。\n5. 選衣著模式（依原圖／依場景／依描述）。\n6. 看點數後生成。","text_en":"## How to use it\n1. Open `/promo-camera` and choose **Portrait**.\n2. Upload a person reference.\n3. Pick a shoot theme and scene. Optional product or scene photo.\n4. Pick a **render style**: clear / mood / hybrid / looser scale (see [/help/promo-camera/portrait-modes](/help/promo-camera/portrait-modes)). Revealing products use Looser scale (Plan 3 / Plan 4).\n5. Pick outfit mode (from reference / scene / description).\n6. Check credits and generate."},
        {"type":"text","sort":2,"text":"## 注意\n- 請使用你有權使用的人像。解析度與點數以頁面為準。寬鬆尺度為 1／4 MP，限方案三／方案四，每帳號每分鐘有次數上限。\n- 人像通用原則（忽略原圖姿勢）每種風格與三種衣著都適用，含證件／正式主題。\n- 大尺度產品請用寬鬆尺度。清晰／氛圍／混合被外部擋下時，不會自動再送。\n- 寬鬆尺度仍可能被外部擋。請換身份參考圖或調整描述。\n- 要高度像本人或證件請用清晰，不要用寬鬆尺度。\n- 管理員可查看氛圍「草稿」或混合「場景底圖」對照。","text_en":"## Notes\n- Use photos you have rights to. Resolution and credits follow the page. Looser scale is 1 / 4 MP, Plan 3 / Plan 4 only, with a per-account per-minute cap.\n- Portrait-wide principles (ignore original pose) apply to every style and outfit mode, including formal ID.\n- Revealing products use Looser scale. If Clear / Mood / Hybrid is blocked by the image API, there is no auto-retry.\n- Looser scale can still be blocked. Change the identity photo or the description.\n- For close likeness or ID photos use Clear, not Looser scale.\n- Admins can compare mood drafts or hybrid empty scenes."}
    ]$hg$::jsonb,
    updated_at = now()
FROM public.help_guide_folders f
WHERE p.folder_id = f.id
  AND f.slug = 'promo-camera'
  AND p.slug = 'portrait';

INSERT INTO public.payment_config (key, value, updated_at)
VALUES ('help_guides_promo_portrait_loose_scale_20260913', '1', now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
